### ISSUE TITLE
Search results go to first item in UITable

### ISSUE THREAD

**Issue by ssabetan** [g0tcha/UITableViewSearch-ios8#1]
Great update to the tutorial, I was testing out the search to use in one of my Apps and I noticed that when you search for something and you select a result, it will segue to that index in the UITableView not in the search results. 

For example, if I search "caramel" and choose the result, it will segue to "chocolate bar" instead of caramel. 

Ideas?

**Comment by g0tcha** [comment]
It's fixed. The issue was that the selected candy was picked from the candies array instead of filteredCandies array. 

Thanks for noticing it!
